#!/bin/bash

if [ $# -ne 1 ]; then
    echo "cppnew - C++ project creation tool - 1.0"
    echo "Usage:"
    echo "        cppnew <project name>"
    echo ""
    exit 1
fi

name=$1

if [ -d $PWD/$name ]; then
    echo "Directory $name already exists"
    exit 1
fi

mkdir -p $PWD/$name/src
cd $name
cp /home/andrea/projects/cpptemplate/CMakePresets.json .

echo "cmake_minimum_required (VERSION 3.8)" > ./CMakeLists.txt
echo "set(VERSION \"1.0.0\")" >> ./CMakeLists.txt
echo "set(CMAKE_CXX_STANDARD 17)" >> ./CMakeLists.txt
echo "set(CMAKE_CXX_STANDARD_REQUIRED ON)" >> ./CMakeLists.txt
echo "set(CMAKE_EXE_LINKER_FLAGS \"-static-libstdc++\")" >> ./CMakeLists.txt
echo "" >> ./CMakeLists.txt
echo "project (\"${name}\")" >> ./CMakeLists.txt
echo "include_directories("\${CMAKE_SOURCE_DIR}/include/")" >> ./CMakeLists.txt
echo "add_executable (${name} src/main.cpp)" >> ./CMakeLists.txt
echo "target_link_libraries(${name} PUBLIC -lpthread)" >> ./CMakeLists.txt
echo ""

cp /home/andrea/projects/cpptemplate/src/main.cpp ./src
sed -i 's/hello/${name}/g' ./CMakeLists.txt

git init .
echo "build/" > .gitignore
git add src/* CMake* .gitignore

echo "Project created"
cd ..
